arson_col_name_fix <- c("YEAR_TWO_DIGIT"     = "YEAR",
                        "REPRTD_KNWN"        = "REPORTED_KNOWN",
                        "MANUFACTURIN$"      = "MANUFACTURING",
                        "ORI_CODE"           = "ORI",
                        "NUMERIC_STATE_CODE" = "STATE",
                        "NUMBER_OF_MONTHS_REPORTED$" = "MONTHS_REPORTED",
                        "NUMBER_OF_MONTHS_REPORTED_see_codebook" = "MONTHS_REPORTED")
arson_year_fix <- c("^1$" = "2001",
                    "^2$" = "2002")

arson_monthly_columns <- c(
  "reported_single_occupancy$",
  "reported_other_residential$",
  "reported_storage$",
  "reported_industry_manufacture$",
  "reported_other_commercial$",
  "reported_community_public$",
  "reported_all_other_structures$",
  "reported_total_structures$",
  "reported_motor_vehicles$",
  "reported_other_mobile$",
  "reported_total_mobile$",
  "reported_all_other$",
  "reported_grand_total$",
  "unfounded_single_occupancy$",
  "unfounded_other_residential$",
  "unfounded_storage$",
  "unfounded_industry_manufacture$",
  "unfounded_other_commercial$",
  "unfounded_community_public$",
  "unfounded_all_other_structures$",
  "unfounded_total_structures$",
  "unfounded_motor_vehicles$",
  "unfounded_other_mobile$",
  "unfounded_total_mobile$",
  "unfounded_all_other$",
  "unfounded_grand_total$",
  "actual_single_occupancy$",
  "actual_other_residential$",
  "actual_storage$",
  "actual_industry_manufacture$",
  "actual_other_commercial$",
  "actual_community_public$",
  "actual_all_other_structures$",
  "actual_total_structures$",
  "actual_motor_vehicles$",
  "actual_other_mobile$",
  "actual_total_mobile$",
  "actual_all_other$",
  "actual_grand_total$",
  "cleared_single_occupancy$",
  "cleared_other_residential$",
  "cleared_storage$",
  "cleared_industry_manufacture$",
  "cleared_other_commercial$",
  "cleared_community_public$",
  "cleared_all_other_structures$",
  "cleared_total_structures$",
  "cleared_motor_vehicles$",
  "cleared_other_mobile$",
  "cleared_total_mobile$",
  "cleared_all_other$",
  "cleared_grand_total$",
  "cleared_18_single_occupancy$",
  "cleared_18_other_residential$",
  "cleared_18_storage$",
  "cleared_18_industry_manufacture$",
  "cleared_18_other_commercial$",
  "cleared_18_community_public$",
  "cleared_18_all_other_structures$",
  "cleared_18_total_structures$",
  "cleared_18_motor_vehicles$",
  "cleared_18_other_mobile$",
  "cleared_18_total_mobile$",
  "cleared_18_all_other$",
  "cleared_18_grand_total$",
  "uninhabited_single_occupancy$",
  "uninhabited_other_residential$",
  "uninhabited_storage$",
  "uninhabited_industry_manufacture$",
  "uninhabited_other_commercial$",
  "uninhabited_community_public$",
  "uninhabited_all_other_structures$",
  "uninhabited_total_structures$",
  "uninhabited_grand_total$",
  "est_damage_single_occupancy$",
  "est_damage_other_residential$",
  "est_damage_storage$",
  "est_damage_industry_manufacture$",
  "est_damage_other_commercial$",
  "est_damage_community_public$",
  "est_damage_all_other_structures$",
  "est_damage_total_structures$",
  "est_damage_motor_vehicles$",
  "est_damage_other_mobile$",
  "est_damage_total_mobile$",
  "est_damage_all_other$",
  "est_damage_grand_total$" )

months_reported_fix <- c("dec last reported"  = "december last reported",
                         "oct last reported"  = "october last reported",
                         "feb last reported"  = "february last reported",
                         "sep last reported"  = "september last reported",
                         "nov last reported"  = "november last reported",
                         "jan last reported"  = "january last reported"
                         )

make_arson_yearly <- function(data, arson_monthly_columns) {
  for (arson_col in arson_monthly_columns) {
    monthly_col       <- grep(arson_col, names(data))
    arson_col         <- gsub("\\$", "", arson_col)
    data[, arson_col] <- rowSums(data[, monthly_col], na.rm = TRUE)
    data              <- data[, -monthly_col]
    if (length(monthly_col) != 12) message(arson_col)
  }
  return(data)
}
