# utils for UCR files

years <- years <- c("^76$"         = "1976",
                    "^99$"         = "1999",
                    "^16$"         = "2016",
                    "^79$"         = "1979",
                    "NOT REPORTED" = NA,
                    "^75$"         = "1975",
                    "^79$"         = "1979",
                    "^80$"         = "1980",
                    "^81$"         = "1981",
                    "^82$"         = "1982")

states <- c("washington, d.c"    = "district of columbia",
            "washington, d"      = "district of columbia",
            "dist of columbia"   = "district of columbia",
            "55"                 = "guam",
            "54"                 = "american samoa",
            "53"                 = "puerto rico",
            "52"                 = "canal zone",
            "99"                 = NA,
            "not reported"       = NA,
            "62"                 = "virgin islands")

division <- c("e. south central"            = "east south central",
              "east st south ceast tral"    = "east south central",
              "west ast t south ceast tral" = "west south central,",
              "east st north central"       = "east north central",
              "west ast t north central"    = "west north central",
              "east st north ceast tral"    = "east north central",
              "west ast t north ceast tral" = "west north central",
              "w. south central"            = "west south central",
              "e. north central"            = "east north central",
              "east st north central"       = "east north central",
              "w. north central"            = "west north central",
              "east st south central"       = "east south central",
              "west ast t south central"    = "west south central",
              "east north ceast tral"       = "east north central",
              "west nceast "                = "west north central",
              "neast  east land"            = "west north central",
              "u. s. posseast sion"         = "possessions",
              "u.s. possessions"            = "possessions",
              "u. s. posessions"            = "possessions",
              " states"                     = "",
              "eng1and"                     = "england",
              "al,ky,ms,tn"                 = "east south central",
              "az,co,id,mt,nv,n"            = "mountain",
              "ar,la,ok, texas"             = "west south central",
              "ak,ca,hi,or,wa"              = "pacific",
              "ct,me,ma,nh"                 = "new england",
              "de,fl,ga,md,nort"            = "south atlantic",
              "il,in,mi,oh,wi"              = "east north central",
              "ia,ks,mn,mo,ne,n"            = "west north central",
              "nj ny pa"                    = "mid-atlantic",
              "w ncen states"               = "west north central",
              "s atlantic sts"              = "south atlantic",
              "0"                           = "possessions",
              "1$"                          = "new england",
              "2"                           = "mid-atlantic",
              "3"                           = "east north central",
              "4"                           = "west north central",
              "5"                           = "south atlantic",
              "6"                           = "east south central",
              "7"                           = "west south central",
              "8"                           = "mountain",
              "9"                           = "pacific",
              "alabama, kentucky, mississippi, tennessee"          = "east south central",
              "arizona, colorado, idaho, montana, nevada, new"     = "mountain",
              "arkansas, louisiana, oklahoma, texas"               = "west south central",
              "alaska, california, hawaii, oregon, washington"     = "pacific",
              "connecticut, maine, massachusetts, new hampshire,"  = "new enland",
              "delaware, florida, georgia, maryland, north"        = "south atlantic",
              "illinois, indiana, michigan, ohio, wisconsin"       = "east north central",
              "iowa, kansas, minnesota, missouri, nebraska, north" ="west north central",
              "new jersey, new york, pennsylvania"                 = "mid-atlantic",
              "midd1east atlantic"          = "mid-atlantic",
              "midast atlantic"             = "mid-atlantic",
              "^u$"                         = NA,
              "e\\."                        = "east ",
              "w\\."                        = "west ",
              "cntrl"                       = "central",
              "middle"                      = "mid",
              "east st south ceast tral"    = "east south central",
              "west ast t south ceast tral" = "west south central",
              "posseast sions"              = "possessions",
              "west nceast "                = "west north central",
              "east st north ceast tral"    = "east north central",
              "new enland"                  = "new england",
              "w ncen"                      = "west north central",
              "midd1e atlantic"             = "mid-atlantic",
              "mid "                        = "mid-",
              "u. s. possession"            = "possessions",
              ":.*"                         = "")

group_number <- c("cit\\. |cit |citie "                  = "cities ",
                  " co\\.|cntys|countie$|countys|cnties" = " counties",
                  "smsa"                                 = "msa",
                  " < "                                  = " under ",
                  " \\+| up| or over"                    = "+",
                  "\\.9"                                 = "",
                  "k"                                    = ",000",
                  "cities,"                              = "cities ",
                  " st "                                 = " state ",
                  "non-msa"                              = "nonmsa",
                  "-"                                    = " thru " ,
                  "nonmsa"                               = "non-msa",
                  "7b"                                   = NA,
                  " between | from | bet "               = " ",
                  " and | through "                      = " thru ",
                  "50 "                                  = "50,000 ",
                  "100$"                                 = "100,000",
                  "25 "                                  = "25,000 ",
                  "50$"                                  = "50,000",
                  "2\\.5 "                               = "2,500 ",
                  "25$"                                  = "25,000",
                  "100 "                                 = "100,000 ",
                  " +"                                   = " ",
                  "^0$"                                  = "possessions",
                  "^cities 10 thru 249,000$"  = "cities 10,000 thru 249,999",
                  "^cities 25,000 thru 10$"   = "cities 25,000 thru 99,999",
                  "possessions.*"             = "possessions",
                  "^8d$" = "non-msa counties under 10,000",
                  "^9a$" = "msa counties 100,000+",
                  "^4$"  = "cities 25,000 thru 49,999",
                  "^1c$" = "cities 250,000 thru 499,999",
                  "^5$"  = "cities 10,000 thru 24,999",
                  "^6$"  = "cities 2,500 thru 9,999",
                  "^7$"  = "cities under 2,500",
                  "^2$"  = "cities 100,000 thru 249,999",
                  "^9c$" = "msa counties 10,000 thru 24,999",
                  "^9d$" = "msa counties under 10,000",
                  "^9b$" = "msa counties 25,000 thru 99,999",
                  "^8c$" = "non-msa counties 10,000 thru 24,999",
                  "^8b$" = "non-msa counties 25,000 thru 99,999",
                  "^3$"  = "cities 50,000 thru 99,999",
                  "^1a$" = "cities 1,000,000 or over",
                  "^1b$" = "cities 500,000 thru 999,999",
                  "^9e$" = "msa state police",
                  "^8e$" = "non-msa state police",
                  "^8a$" = "non-msa counties 100,000+",
                  "all cities 250+$" = "all cities 250,000+",
                  "all "             = "",
                  "thru 49,000"      = "thru 49,999",
                  "10 thru 24,000"   = "10,000 thru 24,999",
                  "thru 9,000"       = "thru 9,999",
                  "thru 249,000"     = "thru 249,999",
                  "thru 99,000"      = "thru 99,999",
                  "2.5,000"          = "2,500",
                  "thru 9,000"       = "thru 9,999",
                  "cities"           = "city",
                  "thru 10$"         = "thru 9,999",
                  "thru 50,000"      = "thru 49,999",
                  "thru 100,000"     = "thru 99,999",
                  "thru 250,000"     = "thru 249,999",
                  "thru 24,000"      = "thru 24,999",
                  "250\\+"           = "250,000+",
                  "2.5$"             = "2,500",
                  "10 thru 25,000"   = "10,000 thru 24,999",
                  " or over"         = "+",
                  "\\+\\+"           = "+",
                  "counties"         = "county"
)

save_files <- function(data, year, file_name, save_name) {
  assign(paste0(file_name, year), data) # Change name
  Write(codebook(data),
        file = paste0(file_name, "codebook_", year, ".txt"))

  save( list = paste0(file_name, year),
        file = paste0(save_name, year, ".rda"))
  do.call("write_dta", list(as.name(paste0(file_name, year)),
                            path = paste0(save_name,
                                          year, ".dta")))
  do.call("write_csv", list(as.name(paste0(file_name, year)),
                            path = paste0(save_name,
                                          year, ".csv")))
  do.call("write_sav", list(as.name(paste0(file_name, year)),
                            path = paste0(save_name,
                                          year, ".sav")))
  do.call("rm", list(as.name(paste0(file_name, year))))
}

save_as_zip <- function(file_name) {
  file_ext <- c("rda", "dta", "csv", "sav")
  all_files <- list.files()
  codebooks <- all_files[grep("codebook", all_files)]
  for (i in seq_along(file_ext)) {
    zip_files <- all_files[grep(file_ext[i], all_files)]
    zip_files <- c(zip_files, codebooks)

    zip::zip(zipfile = paste0(file_name,
                              file_ext[i], ".zip"),
             files = zip_files)
  }
}

save_raw_as_zip <- function(file_name) {
  all_files <- list.files()
  zip::zip(zipfile = paste0(file_name, ".zip"),
           files = all_files)
}