nibrs_window_recovered_property_segment

This setup file was created using the R package asciiSetupReader(version 2.5.0) on 2022-10-06 05:18:41. For any feedback or problems (or if the file looks odd), please make a report on https://github.com/jacobkap/asciiSetupReader/issues. For more information on this package see here: https://jacobkap.github.io/asciiSetupReader/.


data list
V1       1-2
V2       3-4
V3       5-13
V4       14-25
V5       26-33
V6       34
V7       35-36
V8       37-45
V9       46-53
V10      54-55
V11      56-57
V12      58
V13      59-67
V14      68-70
V15      71-72
V16      73
V17      74-82
V18      83-85
V19      86-87
V20      88
V21      89-97
V22      98-100
V23      101-102
V24      103-105
V25      106-108
V26      109-111
V27      112-114
V28      115-117
V29      118-120
V30      121-123
V31      124-126
V32      127-129
V33      130-132
.

variable labels
V1       "segment_level"
V2       "state"
V3       "ori"
V4       "incident_number"
V5       "incident_date"
V6       "type_of_property_loss"
V7       "property_description"
V8       "value_of_property"
V9       "date_recovered"
V10      "number_of_stolen_motor_vehicles"
V11      "num_of_recovered_motor_vehicles"
V12      "suspected_drug_type_1"
V13      "estimated_quantity_1"
V14      "est_quantity_fractional_1000th1"
V15      "type_of_measurement_1"
V16      "suspected_drug_type_2"
V17      "estimated_quantity_2"
V18      "est_quantity_fractional_1000th2"
V19      "type_of_measurement_2"
V20      "suspected_drug_type_3"
V21      "estimated_quantity_3"
V22      "est_quantity_fractional_1000th3"
V23      "type_of_measurement_3"
V24      "ucr_offense_code_1"
V25      "ucr_offense_code_2"
V26      "ucr_offense_code_3"
V27      "ucr_offense_code_4"
V28      "ucr_offense_code_5"
V29      "ucr_offense_code_6"
V30      "ucr_offense_code_7"
V31      "ucr_offense_code_8"
V32      "ucr_offense_code_9"
V33      "ucr_offense_code_10"
.

value labels
V2               
'50'             "Alaska"
'01'             "Alabama"
'03'             "Arkansas"
'54'             "American Samoa"
'02'             "Arizona"
'04'             "California"
'05'             "Colorado"
'06'             "Connecticut"
'52'             "Canal Zone"
'08'             "District of Columbia"
'07'             "Delaware"
'09'             "Florida"
'10'             "Georgia"
'55'             "Guam"
'51'             "Hawaii"
'14'             "Iowa"
'11'             "Idaho"
'12'             "Illinois"
'13'             "Indiana"
'15'             "Kansas"
'16'             "Kentucky"
'17'             "Louisiana"
'20'             "Massachusetts"
'19'             "Maryland"
'18'             "Maine"
'21'             "Michigan"
'22'             "Minnesota"
'24'             "Missouri"
'23'             "Mississippi"
'25'             "Montana"
'26'             "Nebraska"
'32'             "North Carolina"
'33'             "North Dakota"
'28'             "New Hampshire"
'29'             "New Jersey"
'30'             "New Mexico"
'27'             "Nevada"
'31'             "New York"
'34'             "Ohio"
'35'             "Oklahoma"
'36'             "Oregon"
'37'             "Pennsylvania"
'53'             "Puerto Rico"
'38'             "Rhode Island"
'39'             "South Carolina"
'40'             "South Dakota"
'41'             "Tennessee"
'42'             "Texas"
'43'             "Utah"
'62'             "Virgin Islands"
'45'             "Virginia"
'44'             "Vermont"
'46'             "Washington"
'48'             "Wisconsin"
'47'             "West Virginia"
'49'             "Wyoming"
V15              
'GM'             "gram"
'KG'             "kilogram"
'OZ'             "ounce"
'LB'             "pound"
'ML'             "milliliter"
'LT'             "liter"
'FO'             "fluid ounce"
'GL'             "gallon"
'DU'             "dosage unit/items (pills, etc.)"
'NP'             "number of plants"
'XX'             "not reported"
V12              
'A'              "crack cocaine"
'B'              "cocaine (all forms except crack)"
'C'              "hashish"
'D'              "heroin"
'E'              "marijuana"
'F'              "morphine"
'G'              "opium"
'H'              "other narcotics: codeine, demerol, dihydromorphinone or dilaudid, hydrocodone or percodan, methadone, etc."
'I'              "LSD"
'K'              "other hallucinogrens: BMDA (white acid), DMT, MDA, MDMA, mescaline or peyote, psilocybin, STP, etc."
'L'              "amphetamines/methamphetamines"
'M'              "other stimulants: adipex, fastine and ionamin (derivatives of phentermine), benzedrine, didrex, methylphenidate or ritalin, phenmetrazine or preludin, tenuate, etc."
'N'              "barbiturates"
'O'              "other depressants: glutethimide or doriden, methaqualone or quaalude, pentazocine or talwin, etc."
'P'              "other drugs: antidepressants (elavil, triavil, tofranil, etc.), aromatic hydrocarbons, propoxyphene or darvon, tranquilizers (chlordiazepoxide or librium, diazepam or valium, etc.), etc."
'U'              "unknown type drug"
'X'              "over 3 drug types"
'J'              "PCP"
V19              
'GM'             "gram"
'KG'             "kilogram"
'OZ'             "ounce"
'LB'             "pound"
'ML'             "milliliter"
'LT'             "liter"
'FO'             "fluid ounce"
'GL'             "gallon"
'DU'             "dosage unit/items (pills, etc.)"
'NP'             "number of plants"
'XX'             "not reported"
V16              
'A'              "crack cocaine"
'B'              "cocaine (all forms except crack)"
'C'              "hashish"
'D'              "heroin"
'E'              "marijuana"
'F'              "morphine"
'G'              "opium"
'H'              "other narcotics: codeine, demerol, dihydromorphinone or dilaudid, hydrocodone or percodan, methadone, etc."
'I'              "LSD"
'K'              "other hallucinogrens: BMDA (white acid), DMT, MDA, MDMA, mescaline or peyote, psilocybin, STP, etc."
'L'              "amphetamines/methamphetamines"
'M'              "other stimulants: adipex, fastine and ionamin (derivatives of phentermine), benzedrine, didrex, methylphenidate or ritalin, phenmetrazine or preludin, tenuate, etc."
'N'              "barbiturates"
'O'              "other depressants: glutethimide or doriden, methaqualone or quaalude, pentazocine or talwin, etc."
'P'              "other drugs: antidepressants (elavil, triavil, tofranil, etc.), aromatic hydrocarbons, propoxyphene or darvon, tranquilizers (chlordiazepoxide or librium, diazepam or valium, etc.), etc."
'U'              "unknown type drug"
'X'              "over 3 drug types"
'J'              "PCP"
V23              
'GM'             "gram"
'KG'             "kilogram"
'OZ'             "ounce"
'LB'             "pound"
'ML'             "milliliter"
'LT'             "liter"
'FO'             "fluid ounce"
'GL'             "gallon"
'DU'             "dosage unit/items (pills, etc.)"
'NP'             "number of plants"
'XX'             "not reported"
V20              
'A'              "crack cocaine"
'B'              "cocaine (all forms except crack)"
'C'              "hashish"
'D'              "heroin"
'E'              "marijuana"
'F'              "morphine"
'G'              "opium"
'H'              "other narcotics: codeine, demerol, dihydromorphinone or dilaudid, hydrocodone or percodan, methadone, etc."
'I'              "LSD"
'K'              "other hallucinogrens: BMDA (white acid), DMT, MDA, MDMA, mescaline or peyote, psilocybin, STP, etc."
'L'              "amphetamines/methamphetamines"
'M'              "other stimulants: adipex, fastine and ionamin (derivatives of phentermine), benzedrine, didrex, methylphenidate or ritalin, phenmetrazine or preludin, tenuate, etc."
'N'              "barbiturates"
'O'              "other depressants: glutethimide or doriden, methaqualone or quaalude, pentazocine or talwin, etc."
'P'              "other drugs: antidepressants (elavil, triavil, tofranil, etc.), aromatic hydrocarbons, propoxyphene or darvon, tranquilizers (chlordiazepoxide or librium, diazepam or valium, etc.), etc."
'U'              "unknown type drug"
'X'              "over 3 drug types"
'J'              "PCP"
V6               
'1'              "none"
'2'              "burned"
'3'              "counterfeited/forged"
'4'              "destroyed/damaged/vandalized"
'5'              "recovered"
'6'              "seized"
'7'              "stolen/etc. (includes bribed, defrauded, embezzled, extorted, ransomed, robbed, etc.)"
'8'              "unknown"
V7               
'01'             "aircraft"
'02'             "alcohol"
'03'             "automobiles"
'04'             "bicycles"
'05'             "buses"
'06'             "clothes/furs"
'07'             "computer hardware/software"
'08'             "consumable goods"
'09'             "credit/debit cards"
'10'             "drugs/narcotics"
'11'             "drug/narcotic equipment"
'12'             "farm equipment"
'13'             "firearms"
'14'             "gambling equipment"
'15'             "heavy construction/industrial equipment"
'16'             "household goods"
'17'             "jewelry/precious metals"
'18'             "livestock"
'19'             "merchandise"
'20'             "money"
'21'             "negotiable instruments"
'22'             "nonnegotiable instruments"
'23'             "office-type equipment"
'24'             "other motor vehicles"
'25'             "purses/handbags/wallets"
'26'             "radios/TVs/VCRs"
'27'             "recordings - audio/visual"
'28'             "recreational vehicles"
'29'             "structures - single occupancy dwellings"
'30'             "structures - other dwellings"
'31'             "structures - commercial/business"
'32'             "structures - industrial manufacturing"
'33'             "structures - public/community"
'34'             "structures - storage"
'35'             "structures - other"
'36'             "tools - power/hand"
'37'             "trucks"
'38'             "vehicle parts/accessories"
'39'             "watercraft"
'77'             "other"
'88'             "pending inventory (of property)"
'99'             "special category"
'41'             "aircraft parts/accessories"
'42'             "artistic supplies/accessories"
'43'             "building materials"
'44'             "camping/hunting/fishing equipment/supplies"
'45'             "chemicals"
'46'             "collections/collectibles"
'47'             "crops"
'48'             "documents - personal or business"
'49'             "explosives"
'59'             "firearm accessories"
'64'             "fuel"
'65'             "identity documents"
'66'             "identity - intangible"
'67'             "law enforcement equipment"
'68'             "lawn/yard/garden equipment"
'69'             "logging equipment"
'70'             "medical/medical lab equipment"
'71'             "metals, non-precious"
'72'             "musical instruments"
'73'             "pets"
'74'             "photographic/optical equipment"
'75'             "portible electronic communications"
'76'             "recreational/sports equipment"
'78'             "trailers"
'79'             "watercraft equipment/parts/accessories"
'80'             "weapons - other"
V8               
'000000001'      "unknown"
V24              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V25              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V26              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V27              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V28              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V29              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V30              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V31              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V32              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
V33              
'200'            "arson"
'13A'            "aggravated assault"
'13B'            "simple assault"
'13C'            "intimidation"
'510'            "bribery"
'220'            "burglary/breaking and entering"
'250'            "counterfeiting/forgery"
'290'            "destruction/damage/vandalism of property"
'35A'            "drug/narcotic violations"
'35B'            "drug equipment violations"
'270'            "embezzlement"
'210'            "extortion/blackmail"
'26A'            "false pretenses/swindle/confidence game"
'26B'            "credit card/atm fraud"
'26C'            "impersonation"
'26D'            "welfare fraud"
'26E'            "wire fraud"
'26F'            "identity theft"
'39A'            "betting/wagering"
'39B'            "operating/promoting/assisting gambling"
'39C'            "gambling equipment violations"
'39D'            "sports tampering"
'09A'            "murder/nonnegligent manslaughter"
'09B'            "negligent manslaughter"
'09C'            "justifiable homicide"
'100'            "kidnapping/abduction"
'23A'            "pocket-picking"
'23B'            "purse-snatching"
'23C'            "shoplifting"
'23D'            "theft from building"
'23E'            "theft from coin-operated machine or device"
'23F'            "theft from motor vehicle"
'23G'            "theft of motor vehicle parts/accessories"
'23H'            "all other larceny"
'240'            "motor vehicle theft"
'370'            "pornography/obscene material"
'40A'            "prostitution"
'40B'            "assisting or promoting prostitution"
'120'            "robbery"
'11A'            "rape"
'11B'            "sodomy"
'11C'            "sexual assault with an object"
'11D'            "fondling (incident liberties/child molest)"
'36A'            "incest"
'36B'            "statutory rape"
'280'            "stolen property offenses (receiving, selling, etc.)"
'520'            "weapon law violations"
'90A'            "bad checks"
'90B'            "curfew/loitering/vagrancy violations"
'90C'            "disorderly conduct"
'90D'            "driving under the influence"
'90E'            "drunkenness"
'90F'            "family offenses, nonviolent"
'90G'            "liquor law violations"
'90H'            "peeping tom"
'90I'            "runaway"
'90J'            "trespass of real property"
'90Z'            "all other offenses"
'26F'            "identity theft"
'26G'            "hacking/computer invasion"
'40C'            "purchasing prostitution"
'64A'            "human trafficking - commercial sex acts"
'64B'            "human trafficking - involuntary servitude"
'720'            "animal cruelty"
.



execute
