setup_files/nibrs_window_arrestee_segment

This setup file was created using the R package asciiSetupReader(version 2.5.2) on 2025-08-10 02:22:28.042449. For any feedback or problems (or if the file looks odd), please make a report on https://github.com/jacobkap/asciiSetupReader/issues. For more information on this package see here: https://jacobkap.github.io/asciiSetupReader/.


data list
V1       1-2
V2       3-4
V3       5-13
V4       14-25
V5       26-33
V6       34-35
V7       36-47
V8       48-55
V9       56
V10      57
V11      58-60
V12      61-62
V13      63
V14      64-65
V15      66
V16      67-68
V17      69
V18      70
V19      71
V20      72
V21      73
V22      74
V23      75-77
V24      78-80
V25      81-83
V26      84-86
V27      87-89
V28      90-92
V29      93-95
V30      96-98
V31      99-101
V32      102-104
.

variable labels
V1       "segment_level"
V2       "state"
V3       "ori"
V4       "incident_number"
V5       "incident_date"
V6       "arrestee_sequence_number"
V7       "arrest_transaction_number"
V8       "arrest_date"
V9       "type_of_arrest"
V10      "multiple_arrestee_indicator"
V11      "ucr_arrest_offense_code"
V12      "arrestee_weapon_1"
V13      "automatic_weapon_indicator_1"
V14      "arrestee_weapon_2"
V15      "automatic_weapon_indicator_2"
V16      "age_of_arrestee"
V17      "sex_of_arrestee"
V18      "race_of_arrestee"
V19      "ethnicity_of_arrestee"
V20      "resident_status_of_arrestee"
V21      "disposition_of_arrestee_under18"
V22      "window_clearance_flag"
V23      "ucr_offense_code_1"
V24      "ucr_offense_code_2"
V25      "ucr_offense_code_3"
V26      "ucr_offense_code_4"
V27      "ucr_offense_code_5"
V28      "ucr_offense_code_6"
V29      "ucr_offense_code_7"
V30      "ucr_offense_code_8"
V31      "ucr_offense_code_9"
V32      "ucr_offense_code_10"
.

value labels
V2         
'50'       "Alaska"
'01'       "Alabama"
'03'       "Arkansas"
'54'       "American Samoa"
'02'       "Arizona"
'04'       "California"
'05'       "Colorado"
'06'       "Connecticut"
'52'       "Canal Zone"
'08'       "District of Columbia"
'07'       "Delaware"
'09'       "Florida"
'10'       "Georgia"
'55'       "Guam"
'51'       "Hawaii"
'14'       "Iowa"
'11'       "Idaho"
'12'       "Illinois"
'13'       "Indiana"
'15'       "Kansas"
'16'       "Kentucky"
'17'       "Louisiana"
'20'       "Massachusetts"
'19'       "Maryland"
'18'       "Maine"
'21'       "Michigan"
'22'       "Minnesota"
'24'       "Missouri"
'23'       "Mississippi"
'25'       "Montana"
'26'       "Nebraska"
'32'       "North Carolina"
'33'       "North Dakota"
'28'       "New Hampshire"
'29'       "New Jersey"
'30'       "New Mexico"
'27'       "Nevada"
'31'       "New York"
'34'       "Ohio"
'35'       "Oklahoma"
'36'       "Oregon"
'37'       "Pennsylvania"
'53'       "Puerto Rico"
'38'       "Rhode Island"
'39'       "South Carolina"
'40'       "South Dakota"
'41'       "Tennessee"
'42'       "Texas"
'43'       "Utah"
'62'       "Virgin Islands"
'45'       "Virginia"
'44'       "Vermont"
'46'       "Washington"
'48'       "Wisconsin"
'47'       "West Virginia"
'49'       "Wyoming"
V9         
'O'        "on-view arrest (taken into custody without a warrant or previous incident report)"
'S'        "summoned/cited (not taken into custody)"
'T'        "taken into custody (based on warrant and/or previous incident report)"
V11        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V12        
'01'       "unarmed"
'11'       "firearm (type not stated)"
'12'       "handgun"
'13'       "rifle"
'14'       "shotgun"
'15'       "other firearm"
'16'       "lethal cutting instrument (knife, ice pick, screwdriver, ax, etc.)"
'17'       "blunt object (e.g., club/blackjack/brass knuckles)"
V13        
'A'        "automatic weapon"
V14        
'01'       "unarmed"
'11'       "firearm (type not stated)"
'12'       "handgun"
'13'       "rifle"
'14'       "shotgun"
'15'       "other firearm"
'16'       "lethal cutting instrument (knife, ice pick, screwdriver, ax, etc.)"
'17'       "blunt object (e.g., club/blackjack/brass knuckles)"
V15        
'A'        "automatic weapon"
V16        
'00'       "unknown"
'99'       "over 98 years old"
'NN'       "under 24 hours (neonate)"
'NB'       "1 to 6 days old (newborn)"
'BB'       "between 6 days and 1 year old (baby)"
V17        
'M'        "male"
'm'        "male"
'f'        "female"
'F'        "female"
'U'        "unknown"
V18        
'W'        "white"
'B'        "black"
'I'        "american indian/alaskan native"
'A'        "asian"
'U'        "unknown"
'P'        "native hawaiian or other pacific islander"
'M'        "unknown"
V19        
'H'        "hispanic or latino"
'N'        "not hispanic or latino"
'U'        "unknown"
V20        
'R'        "resident"
'r'        "resident"
'N'        "nonresident"
'U'        "unknown"
V21        
'H'        "handled within department (released to parents, released with warning, etc.)"
'R'        "referred to other authorities (turned over to juvenile court, probation department, welfare agency, other police agency, criminal or adult court, etc.)"
V10        
'M'        "multiple"
'm'        "multiple"
'C'        "count arrestee"
'c'        "count arrestee"
'N'        "not applicable"
'n'        "not applicable"
V22        
'Y'        "yes (clears the case)"
'N'        "no (already cleared)"
V23        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V24        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V25        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V26        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V27        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V28        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V29        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V30        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V31        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
V32        
'200'      "arson"
'13A'      "assault offenses - aggravated assault"
'13B'      "assault offenses - simple assault"
'13C'      "assault offenses - intimidation"
'510'      "bribery"
'220'      "burglary/breaking and entering"
'250'      "counterfeiting/forgery"
'290'      "destruction/damage/vandalism of property"
'35A'      "drug/narcotic offenses - drug/narcotic violations"
'35B'      "drug/narcotic offenses - drug equipment violations"
'270'      "embezzlement"
'210'      "extortion/blackmail"
'26A'      "fraud offenses - false pretenses/swindle/confidence game"
'26B'      "fraud offenses - credit card/atm fraud"
'26C'      "fraud offenses - impersonation"
'26D'      "fraud offenses - welfare fraud"
'26E'      "fraud offenses - wire fraud"
'26F'      "fraud offenses - identity theft"
'39A'      "gambling offenses - betting/wagering"
'39B'      "gambling offenses - operating/promoting/assisting gambling"
'39C'      "gambling offenses - gambling equipment violations"
'39D'      "gambling offenses - sports tampering"
'09A'      "murder/nonnegligent manslaughter"
'09B'      "negligent manslaughter"
'100'      "kidnapping/abduction"
'23A'      "larceny/theft offenses - pocket-picking"
'23B'      "larceny/theft offenses - purse-snatching"
'23C'      "larceny/theft offenses - shoplifting"
'23D'      "larceny/theft offenses - theft from building"
'23E'      "larceny/theft offenses - theft from coin-operated machine or device"
'23F'      "larceny/theft offenses - theft from motor vehicle"
'23G'      "larceny/theft offenses - theft of motor vehicle parts/accessories"
'23H'      "larceny/theft offenses - all other larceny"
'240'      "motor vehicle theft"
'370'      "pornography/obscene material"
'40A'      "prostitution offenses - prostitution"
'40B'      "prostitution offenses - assisting or promoting prostitution"
'120'      "robbery"
'11A'      "sex offenses - rape"
'11B'      "sex offenses - sodomy"
'11C'      "sex offenses - sexual assault with an object"
'11D'      "sex offenses - criminal sexual contact (formerly: fondling (indecent liberties/child molest))"
'36A'      "sex offenses - incest"
'36B'      "sex offenses - statutory rape"
'280'      "stolen property offenses (receiving, selling, etc.)"
'520'      "weapon law violations - weapon law violations"
'90A'      "bad checks"
'90B'      "curfew/loitering/vagrancy violations"
'90C'      "disorderly conduct"
'90D'      "driving under the influence"
'90E'      "drunkenness"
'90F'      "family offenses, nonviolent"
'90G'      "liquor law violations"
'90H'      "peeping tom"
'90I'      "runaway"
'90J'      "trespass of real property"
'90Z'      "all other offenses"
'26F'      "fraud offenses - identity theft"
'26G'      "fraud offenses - hacking/computer invasion"
'40C'      "prostitution offenses - purchasing prostitution"
'64A'      "human trafficking - commercial sex acts"
'64B'      "human trafficking - involuntary servitude"
'720'      "animal cruelty"
'09C'      "justifiable homicide - not a crime"
'58A'      "commerce violations - import violations"
'58B'      "commerce violations - export Violations"
'61A'      "commerce violations - federal liquor offenses"
'61B'      "commerce violations - federal tobacco offenses"
'620'      "commerce violations - wildlife trafficking"
'30A'      "immigration violations - illegal entry into the united states"
'30B'      "immigration violations - false citizenship"
'30C'      "immigration violations - smuggling aliens"
'30D'      "immigration violations - re-entry into the united states after deportation"
'49A'      "fugitive offenses - harboring escapee - concealing from arrest"
'49B'      "fugitive offenses - flight to avoid prosecution"
'49C'      "fugitive offenses - flight to avoid deportation"
'360'      "sex offenses - failure to register as a sex offender"
'101'      "treason"
'521'      "weapon law violations - violation of national firearm act of 1934"
'522'      "weapon law violations - weapons of mass destruction"
'526'      "weapon law violations - explosives"
'90K'      "bond default - failure to appear"
'90L'      "federal resource violations"
'90M'      "perjury"
'26H'      "fraud offenses - money laundering"
'103'      "espionage"
.



execute
