misc_cols <- c("population_group",
               "country_division",
               "country_region",
               "core_city",
               "covered_by_ori",
               "fbi_field_office",
               "judicial_district",
               "agency_nibrs_flag",
               "agency_inactive_date",
               "date_ori_was_added")


offender_race_as_group_fix <- c("^am indian/ak native$"       = "american indian or native alaskan",
                                "^asian$"                     = "asian or pacific islander",
                                "^asian/pacific islander$"                     = "asian or pacific islander",
                                "^black or african american$" = "black",
                                "^native hawaiian/other pacific islander$" = "native hawaiian or other pacific islander",
                                "^p$"                         = NA)

core_city_fix <- c("^yes$" = "core city",
                   "^no$" = "not a core city")

population_group_fix <- c("^0$"  = "possessions",
                          "^1$" = "city 250,000+",
                          "^1A$" = "city 1,000,000+",
                          "^1B$" = "city 500,000 thru 999,999",
                          "^1C$" = "city 250,000 thru 499,999",
                          "^2$"  = "city 100,000 thru 249,999",
                          "^3$"  = "city 50,000 thru 99,999",
                          "^4$"  = "city 25,000 thru 49,999",
                          "^5$"  = "city 10,000 thru 24,999",
                          "^6$"  = "city 2,500 thru 9,999",
                          "^7$"  = "city under 2,500",
                          "^8$"  = "non-msa county",
                          "^8A$" = "non-msa county 100,000+",
                          "^8B$" = "non-msa county 25,000 thru 99,999",
                          "^8C$" = "non-msa county 10,000 thru 24,999",
                          "^8D$" = "non-msa county under 10,000",
                          "^8E$" = "non-msa state police",
                          "^9$"  = "msa-county",
                          "^9A$" = "msa-county 100,000+",
                          "^9B$" = "msa-county 25,000 thru 99,999",
                          "^9C$" = "msa-county 10,000 thru 24,999",
                          "^9D$" = "msa-county under 10,000")

ucr_offense_codes_fix <- c( "^agg asslt$"            = "aggravated assault",
                            "^simple asslt$"         = "simple assault",
                            "^burg/b & e$"           = "burglary, breaking and entering",
                            "^drug/narc violations$" = "drug/narcotic violations",
                            "^theft of mv parts$"    = "theft of motor vehicle parts",
                            "^sex asslt w/object$"   = "sexual assault with object",
                            "^false pretenses/swindle/conf game$" = "false pretenses/swindle/confidence game",
                            "^murder/non-neg manslaughter$" = "murder/non-negligent manslaughter",
                            "^extort/blackmail$"            = "extortion/blackmail",
                            "^destruct/vandalism$"          = "destruction of property/vandalism",
                            "^theft from coin-op machine$"  = "theft from coin-operated machine",
                            "^drug equip violations$"       = "drug equipment violations",

                            "^burglary, breaking and entering$"  = "Burglary/Breaking and Entering",
                            "^counterfeit/forgery$"              = "Counterfeiting/Forgery",
                            "^fondling \\(indecent liberties/child molesting\\)$" = "Forcible Fondling - Indecent Liberties/Child Molest",
                            "^forcible fondling$"                = "Forcible Fondling - Indecent Liberties/Child Molest",
                            "^rape$"                             = "forcible rape",
                            "^sexual assault with object$"       = "Sexual Assault With An Object",
                            "^sodomy$"                           = "forcible sodomy",
                            "^stolen property offenses$"         = "Stolen Property Offenses - Receiving, Selling, etc.",
                            "^theft from coin-operated machine$" = "Theft From Coin-operated Machine or Device",
                            "^theft of motor vehicle parts$"     = "Theft of Motor Vehicle Parts/Accessories",
                            "^assist prostitution$"              = "Assisting or Promoting Prostitution",
                            "^26f$"                              = NA)

bias_motivation_fix <- c("^anti-am indian$"                 = "anti-american indian",
                         "^anti-american indian$"           = "anti-american indian or native alaskan",
                         "^anti-american indian or alaska native$" = "anti-american indian or native alaskan",
                         "^anti-black or african american$" = "anti-black",
                         "^anti-asian$"                     = "Anti-Asian or Pacific Islander",
                         "^anti-female homosexual$"         = "Anti-Female Homosexual (Lesbian)",
                         "^anti-hispanic or latino$"        = "anti-hispanic",
                         "^anti-homosexual \\(both\\)$"     = "Anti-Homosexual (Gay and Lesbian)",
                         "^anti-islamic$"                   = "anti-muslim",
                         "^anti-male homosexual$"           = "Anti-Male Homosexual (Gay)",
                         "^anti-not hispanic or latino$"    = "anti-not hispanic",
                         "^anti-other ethnicity$"           = "Anti-not hispanic",
                         "^anti-multi-racial$"              = "anti-multi-racial group",
                         "^anti-multi-religious$"           = "anti-multi-religious group")




location_fix <- c("^drug store/dr office/hosp$"      = "drug store/doctors office/hospital",
                  "^rental stor. facil.$"            = "rental storage facility",
                  "^bank$"                           = "bank/savings and loan",
                  "^bar$"                            = "bar/nightclub",
                  "^department store$"               = "department/discount store",
                  "^drug store/dr office/hospital$"  = "drug store/doctors office/hospital",
                  "^drug store/drs office/hospital$" = "drug store/doctors office/hospital",
                  "^govt/public building$"           = "government/public building",
                  "^hotel/motel/etc.$"               = "hotel/motel",
                  "^office building$"                = "commercial/office building",
                  "^rental store$"                   = "rental storage facility",
                  "^school--college/university$"     = "school - college/university",
                  "^school--elementary/secondary$"   = "school - elementary/secondary",
                  "^shelter--mission/homeless$"      = "shelter - mission/homeless",
                  "^specialty store$"                = "specialty store - tv, fur, etc.",
                  "specialty store \\(tv, fur, etc.\\)"  = "specialty store - tv, fur, etc.",
                  "^terminal$"                       = "air/bus/train terminal",
                  "^undocumented code$"              = NA)
