source('R/make_sps/make_sps_utils.R')

col_positions <- c("1-2",
                   "3-4",
                   "5-13",
                   "14-25",
                   "26-34",
                   "35-37",
                   "38-40",
                   "41-49",
                   "50-58",
                   "59-61",
                   "62-64",
                   "65-73",
                   "74-82",
                   "83-85",
                   "86-88",
                   "89-97",
                   "98-106",
                   "107-109",
                   "110-112",
                   "113-121",
                   "122-132")

col_labels <- c("segment_level",
                "state",
                "ori",
                "incident_number",
                "current_population_1",
                "ucr_county_code_1",
                "msa_code_1",
                "last_population_1",
                "current_population_2",
                "ucr_county_code_2",
                "msa_code_2",
                "last_population_2",
                "current_population_3",
                "ucr_county_code_3",
                "msa_code_3",
                "last_population_3",
                "current_population_4",
                "ucr_county_code_4",
                "msa_code_4",
                "last_population_4",
                "blank")

make_sps_setup(file_name     = "setup_files/nibrs_batch_header_2",
               col_positions = col_positions,
               col_labels    = col_labels,
               value_labels  =  state_value_labels)
