source(here::here('R/make_sps/make_sps_utils.R'))
source(here::here('R/make_sps/nibrs_sps_utils.R'))
# Page 46-53

col_positions <- c("1-2",
                   "3-4",
                   "5-13",
                   "14-25",
                   "26-33",
                   "34-36",
                   "37",
                   "38",
                   "39",
                   "40",
                   "41-42",
                   "43-44",
                   "45",
                   "46",
                   "47",
                   "48",
                   "49-50",
                   "51",
                   "52-53",
                   "54",
                   "55-56",
                   "57",
                   "58-59")

col_labels <- c("segment_level",
                "state",
                "ori",
                "incident_number",
                "incident_date",
                "ucr_offense_code",
                "offense_attempted_completed",
                "offender_suspected_of_using_1",
                "offender_suspected_of_using_2",
                "offender_suspected_of_using_3",
                "location_type",
                "number_of_premises_entered",
                "method_of_entry",
                "type_criminal_activity_1",
                "type_criminal_activity_2",
                "type_criminal_activity_3",
                "type_weapon_force_involved_1",
                "automatic_weapon_indicator_1",
                "type_weapon_force_involved_2",
                "automatic_weapon_indicator_2",
                "type_weapon_force_involved_3",
                "automatic_weapon_indicator_3",
                "bias_motivation")



nibrs_offense_segment_value_labels_repeated <-
  c("offender_suspected_of_using_replace = ",
    "A = alcohol",
    "C = completer equipment",
    "D = drugs/narcotics",
    "N = not applicable",
    "type_criminal_activity_replace = ",
    "B = buying/receiving",
    "C = cultivating/manufacturing/publishing",
    "D = distributing/selling",
    "E = exploiting children",
    "O = operating/promoting/assisting",
    "P = possessing/concealing",
    "T = transporting/transmitting/importing",
    "U = using/consuming",
    "type_weapon_force_involved_replace = ",
    "11 = firearm (type not stated)",
    "12 = handgun",
    "13 = rifle",
    "14 = shotgun",
    "15 = other firearm",
    "20 = knife/cutting instrument (ice pick, screwdriver, ax, etc.",
    "30 = blunt object (club, hammer, etc.)",
    "35 = motor vehicle",
    "40 = personal weapons (hands, feet, teeth, etc.)",
    "50 = poison (include gas)",
    "60 = explosives",
    "65 = fire/incendiary device",
    "70 = drugs/narcotics/sleeping pills",
    "85 = asphyxiation (by drowning, strangulation, suffocation, gas, etc.)",
    "90 = other",
    "95 = unknown",
    "99 = none",
    "automatic_weapon_indicator_replace = ",
    "A = automatic weapon")
nibrs_offense_segment_value_labels_repeated <-
  repeated_label_replace_fixer(nibrs_offense_segment_value_labels_repeated,
                                                     1:3)

nibrs_offense_segment_value_labels <- c("offense_attempted_completed = ",
                                      "A = attempted",
                                      "C = completed",
                                      "bias_motivation = ",
                                      "11 = white",
                                      "12 = black",
                                      "13 = american indian or alaskan native",
                                      "14 = asian/pacific islander",
                                      "15 = multi-racial group",
                                      "21 = jewish",
                                      "22 = catholic",
                                      "23 = protestant",
                                      "24 = islamic (muslim)",
                                      "25 = other religion",
                                      "26 = multi-religious group",
                                      "27 = atheism/agnosticism",
                                      "31 = arab",
                                      "32 = hispanic",
                                      "33 = other ethnicity/national origin",
                                      "41 = male homosexual (gay)",
                                      "42 = female homosexual (lesbian)",
                                      "43 = homosexual (both gay and lesbian)",
                                      "44 = heterosexual",
                                      "45 = bisexual",
                                      "88 = none",
                                      "99 = unknown",
                                      "method_of_entry = ",
                                      "F = force",
                                      "N = no force",
                                      nibrs_offense_segment_value_labels_repeated)

setwd(here::here("setup_files"))
make_sps_setup(file_name     = "nibrs_offense_segment",
                                 col_positions = col_positions,
                                 col_labels    = col_labels,
                                 value_labels  = nbirs_offense_segment_value_labels)
