source(here::here('R/make_sps/make_sps_utils.R'))
source(here::here('R/make_sps/nibrs_sps_utils.R'))
# Page 72-77

col_positions <- c("1-2",
                   "3-4",
                   "5-13",
                   "14-25",
                   "26-33",
                   "34-35",
                   "36-47",
                   "48-55",
                   "56",
                   "57",
                   "58-60",
                   "61-62",
                   "63",
                   "64-65",
                   "66",
                   "67-68",
                   "69",
                   "70",
                   "71",
                   "72",
                   "73")


col_labels <- c("segment_level",
                "state",
                "ori",
                "incident_number",
                "incident_date",
                "arrestee_sequence_number",
                "arrest_transaction_number",
                "arrest_date",
                "type_of_arrest",
                "multiple_arrestee_segments_indicator",
                "ucr_arrest_offense_code",
                "arrestee_weapon_1",
                "automatic_weapon_indicator_1",
                "arrestee_weapon_2",
                "automatic_weapon_indicator_2",
                "age_of_arrestee",
                "sex_of_arrestee",
                "race_of_arrestee",
                "ethnicity_of_arrestee",
                "resident_status_of_arrestee",
                "disposition_of_arrestee_under_18")

nibrs_arrestee_value_labels <-
  c("type_of_arrest = ",
    "O = on-view arrest (taken into custody without a warrant or previous incident report)",
    "S = summoned/cited (not taken into custody)",
    "T = taken into custody (based on warrant and/or previous incident report)",
    gsub("ucr_offense_code", "ucr_arrest_offense_code", ucr_offense_code_value_labels),
    repeated_label_replace_fixer(c("arrestee_weapon_replace = ",
                                   "01 = unarmed",
                                   "11 = firearm (type not stated)",
                                   "12 = handgun",
                                   "13 = rifle",
                                   "14 = shotgun",
                                   "15 = other firearm",
                                   "16 = lethal cutting instrument (switchblade knife, etc.)",
                                   "17 = club/blackjack/brass knuckles",
                                   "automatic_weapon_indicator_replace = ",
                                   "A = automatic weapon"), 1:2),
    "age_of_arrestee = ",
    "00 = unknown",
    "99 = over 98 years old",
    "sex_of_arrestee = ",
    "M = male",
    "F = female",
    "race_of_arrestee = ",
    "W = white",
    "B = black",
    "I = american indian/alaskan native",
    "A = asian/pacific islander",
    "U = unknown",
    "ethnicity_of_arrestee = ",
    "H = hispanic origin",
    "N = not of hispanic origin",
    "U = unknown",
    "resident_status_of_arrestee = ",
    "R = resident",
    "N = nonresident",
    "U = unknown",
    "disposition_of_arrestee_under_18 = ",
    "H = handled within department (released to parents, released with warning, etc.)",
    "R = referred to other authorities (turned over to juvenile court, probation department, welfare agency, other police agency, criminal or adult court, etc.)")

setwd(here::here("setup_files"))
make_sps_setup(file_name = "nibrs_arrestee_segment",
               col_positions = col_positions,
               col_labels    = col_labels,
               value_labels = c(nibrs_arrestee_value_labels,
                                "multiple_arrestee_segments_indicator = ",
                                "M = multiple",
                                "C = count arrestee",
                                "N = not applicable"))
