source('R/make_sps/make_sps_utils.R')
source('R/make_sps/nibrs_sps_utils.R')
# Page 72-77

col_positions <- c("1-2",
                   "3-4",
                   "5-13",
                   "14-25",
                   "26-33",
                   "34-35",
                   "36-48",
                   "49-56",
                   "57",
                   "58",
                   "59-61",
                   "62-63",
                   "64",
                   "65-66",
                   "67",
                   "68-69",
                   "70",
                   "71",
                   "72",
                   "73",
                   "74")


col_labels <- c("segment_level",
                "state",
                "ori",
                "incident_number",
                "incident_date",
                "arrestee_sequence_number",
                "arrest_transaction_number",
                "arrest_date",
                "type_of_arrest",
                "multiple_arrestee_indicator",
                "ucr_arrest_offense_code",
                "arrestee_weapon_1",
                "automatic_weapon_indicator_1",
                "arrestee_weapon_2",
                "automatic_weapon_indicator_2",
                "age_of_arrestee",
                "sex_of_arrestee",
                "race_of_arrestee",
                "ethnicity_of_arrestee",
                "resident_status_of_arrestee",
                "disposition_of_arrestee_under18")

nibrs_arrestee_value_labels <-
  c(state_value_labels,
    "type_of_arrest = ",
    "O = on-view arrest (taken into custody without a warrant or previous incident report)",
    "S = summoned/cited (not taken into custody)",
    "T = taken into custody (based on warrant and/or previous incident report)",
    gsub("ucr_offense_code", "ucr_arrest_offense_code", ucr_offense_code_value_labels),
    repeated_label_replace_fixer(c("arrestee_weapon_replace = ",
                                   "01 = unarmed",
                                   "11 = firearm (type not stated)",
                                   "12 = handgun",
                                   "13 = rifle",
                                   "14 = shotgun",
                                   "15 = other firearm",
                                   "16 = lethal cutting instrument (knife, ice pick, screwdriver, ax, etc.)",
                                   "17 = blunt object (e.g., club/blackjack/brass knuckles)",
                                   "automatic_weapon_indicator_replace = ",
                                   "A = automatic weapon"), 1:2),
    gsub("replace", "arrestee", age_sex_race_ethnicity),
    "resident_status_of_arrestee = ",
    "R = resident",
    "r = resident",
    "N = nonresident",
    "U = unknown",
    "disposition_of_arrestee_under18 = ",
    "H = handled within department (released to parents, released with warning, etc.)",
    "R = referred to other authorities (turned over to juvenile court, probation department, welfare agency, other police agency, criminal or adult court, etc.)",
    "multiple_arrestee_indicator = ",
    "M = multiple",
    "m = multiple",
    "C = count arrestee",
    "c = count arrestee",
    "N = not applicable",
    "n = not applicable")


make_sps_setup(file_name     = "setup_files/nibrs_arrestee_segment_vermont_2015",
               col_positions = col_positions,
               col_labels    = col_labels,
               value_labels  = nibrs_arrestee_value_labels)
