source('R/make_sps/make_sps_utils.R')
source('R/make_sps/nibrs_sps_utils.R')
# Page 42-45

col_positions <- c("1-2",
                   "3-4",
                   "5-13",
                   "14-25",
                   "26-33",
                   "34",
                   "35-36",
                   "37-38",
                   "39-41",
                   "42-43",
                   "44-45",
                   "46-49",
                   "50",
                   "51-58")

col_labels <- c("segment_level",
                "state",
                "ori",
                "incident_number",
                "incident_date",
                "report_date_indicator",
                "incident_date_hour",
                "total_offense_segments",
                "total_victim_segments",
                "total_offender_segments",
                "total_arrestee_segments",
                "city_submissions",
                "cleared_exceptionally",
                "exceptional_clearance_date")

nibrs_administrative_segment_value_labels <-
  c(state_value_labels,
    "report_date_indicator = ",
    "R = report date",
    " = incident date",
    "incident_date_hour = ",
    "00 = on or between midnight and 00:59",
    "01 = on or between 01:00 and 01:59",
    "02 = on or between 02:00 and 02:59",
    "03 = on or between 03:00 and 03:59",
    "04 = on or between 04:00 and 04:59",
    "05 = on or between 05:00 and 05:59",
    "06 = on or between 06:00 and 06:59",
    "07 = on or between 07:00 and 07:59",
    "08 = on or between 08:00 and 08:59",
    "09 = on or between 09:00 and 09:59",
    "10 = on or between 10:00 and 10:59",
    "11 = on or between 11:00 and 11:59",
    "12 = on or between 12:00 and 12:59",
    "13 = on or between 13:00 and 13:59",
    "14 = on or between 14:00 and 14:59",
    "15 = on or between 15:00 and 15:59",
    "16 = on or between 16:00 and 16:59",
    "17 = on or between 17:00 and 17:59",
    "18 = on or between 18:00 and 18:59",
    "19 = on or between 19:00 and 19:59",
    "20 = on or between 20:00 and 20:59",
    "21 = on or between 21:00 and 21:59",
    "22 = on or between 22:00 and 22:59",
    "23 = on or between 23:00 and 23:59",
    "1- = unknown",
    "2- = unknown",
    "cleared_exceptionally = ",
    "A = death of offender",
    "B = prosecution declined (by the prosecutor for other than lack of probable cause)",
    "C = extradition denied",
    "D = victim refused to cooperate (in the prosecution)",
    "E = juvenile/no custody (the handling of a juvenile without taking him/her into custody, but rather by oral or written notice given to the parents or legal guardian in a case involving a minor offense, such as a petty larceny)",
    "N = not applicable (not cleared exceptionally)")


make_sps_setup(file_name     = "setup_files/nibrs_administrative_segment",
               col_positions = col_positions,
               col_labels    = col_labels,
               value_labels  = nibrs_administrative_segment_value_labels)

